// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Attachment struct {
	ID             uuid.UUID          `db:"id" json:"id"`
	OrganizationID uuid.UUID          `db:"organization_id" json:"organizationId"`
	ProjectID      uuid.UUID          `db:"project_id" json:"projectId"`
	PageID         *uuid.UUID         `db:"page_id" json:"pageId"`
	FileName       string             `db:"file_name" json:"fileName"`
	FileSizeBytes  int64              `db:"file_size_bytes" json:"fileSizeBytes"`
	MimeType       string             `db:"mime_type" json:"mimeType"`
	ObjectStoreKey string             `db:"object_store_key" json:"objectStoreKey"`
	UploadedBy     uuid.UUID          `db:"uploaded_by" json:"uploadedBy"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"createdAt"`
}

type Label struct {
	ID             uuid.UUID `db:"id" json:"id"`
	OrganizationID uuid.UUID `db:"organization_id" json:"organizationId"`
	Name           string    `db:"name" json:"name"`
	ColorHex       *string   `db:"color_hex" json:"colorHex"`
}

type Organization struct {
	ID          uuid.UUID          `db:"id" json:"id"`
	Slug        string             `db:"slug" json:"slug"`
	Name        string             `db:"name" json:"name"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"createdAt"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updatedAt"`
	DisplayName *string            `db:"display_name" json:"displayName"`
	ImageUrl    *string            `db:"image_url" json:"imageUrl"`
	LiveUrl     *string            `db:"live_url" json:"liveUrl"`
	Description *string            `db:"description" json:"description"`
}

type OrganizationMember struct {
	OrganizationID uuid.UUID          `db:"organization_id" json:"organizationId"`
	UserID         uuid.UUID          `db:"user_id" json:"userId"`
	Role           string             `db:"role" json:"role"`
	JoinedAt       pgtype.Timestamptz `db:"joined_at" json:"joinedAt"`
}

type OutboxEvent struct {
	ID             int64              `db:"id" json:"id"`
	OrganizationID uuid.UUID          `db:"organization_id" json:"organizationId"`
	AggregateType  string             `db:"aggregate_type" json:"aggregateType"`
	AggregateID    uuid.UUID          `db:"aggregate_id" json:"aggregateId"`
	EventType      string             `db:"event_type" json:"eventType"`
	Payload        []byte             `db:"payload" json:"payload"`
	Processed      bool               `db:"processed" json:"processed"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"createdAt"`
}

type Page struct {
	ID                      uuid.UUID          `db:"id" json:"id"`
	OrganizationID          uuid.UUID          `db:"organization_id" json:"organizationId"`
	ProjectID               uuid.UUID          `db:"project_id" json:"projectId"`
	SectionID               uuid.UUID          `db:"section_id" json:"sectionId"`
	ParentID                *uuid.UUID         `db:"parent_id" json:"parentId"`
	Title                   string             `db:"title" json:"title"`
	Slug                    string             `db:"slug" json:"slug"`
	Path                    string             `db:"path" json:"path"`
	Position                int32              `db:"position" json:"position"`
	CurrentPublishedVersion int32              `db:"current_published_version" json:"currentPublishedVersion"`
	HasDraft                bool               `db:"has_draft" json:"hasDraft"`
	IsRestricted            bool               `db:"is_restricted" json:"isRestricted"`
	IsArchived              bool               `db:"is_archived" json:"isArchived"`
	CreatedBy               uuid.UUID          `db:"created_by" json:"createdBy"`
	CreatedAt               pgtype.Timestamptz `db:"created_at" json:"createdAt"`
	UpdatedAt               pgtype.Timestamptz `db:"updated_at" json:"updatedAt"`
}

type PageComment struct {
	ID                uuid.UUID          `db:"id" json:"id"`
	OrganizationID    uuid.UUID          `db:"organization_id" json:"organizationId"`
	PageID            uuid.UUID          `db:"page_id" json:"pageId"`
	ParentCommentID   *uuid.UUID         `db:"parent_comment_id" json:"parentCommentId"`
	AuthorID          uuid.UUID          `db:"author_id" json:"authorId"`
	ContentAst        []byte             `db:"content_ast" json:"contentAst"`
	ContentText       string             `db:"content_text" json:"contentText"`
	AnchorFrom        *int32             `db:"anchor_from" json:"anchorFrom"`
	AnchorTo          *int32             `db:"anchor_to" json:"anchorTo"`
	AnchorTextPreview *string            `db:"anchor_text_preview" json:"anchorTextPreview"`
	IsResolved        bool               `db:"is_resolved" json:"isResolved"`
	ResolvedBy        *uuid.UUID         `db:"resolved_by" json:"resolvedBy"`
	ResolvedAt        pgtype.Timestamptz `db:"resolved_at" json:"resolvedAt"`
	DeletedAt         pgtype.Timestamptz `db:"deleted_at" json:"deletedAt"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"createdAt"`
	UpdatedAt         pgtype.Timestamptz `db:"updated_at" json:"updatedAt"`
}

type PageDraft struct {
	PageID          uuid.UUID          `db:"page_id" json:"pageId"`
	OrganizationID  uuid.UUID          `db:"organization_id" json:"organizationId"`
	Title           string             `db:"title" json:"title"`
	ContentAst      []byte             `db:"content_ast" json:"contentAst"`
	BinaryCrdtState []byte             `db:"binary_crdt_state" json:"binaryCrdtState"`
	CreatedBy       uuid.UUID          `db:"created_by" json:"createdBy"`
	UpdatedBy       uuid.UUID          `db:"updated_by" json:"updatedBy"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"createdAt"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updatedAt"`
}

type PageLabel struct {
	PageID  uuid.UUID `db:"page_id" json:"pageId"`
	LabelID uuid.UUID `db:"label_id" json:"labelId"`
}

type PagePermission struct {
	ID         uuid.UUID          `db:"id" json:"id"`
	PageID     uuid.UUID          `db:"page_id" json:"pageId"`
	UserID     *uuid.UUID         `db:"user_id" json:"userId"`
	TeamID     *uuid.UUID         `db:"team_id" json:"teamId"`
	Permission string             `db:"permission" json:"permission"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"createdAt"`
}

type PageRevision struct {
	ID             uuid.UUID          `db:"id" json:"id"`
	OrganizationID uuid.UUID          `db:"organization_id" json:"organizationId"`
	PageID         uuid.UUID          `db:"page_id" json:"pageId"`
	Version        int32              `db:"version" json:"version"`
	Title          string             `db:"title" json:"title"`
	ContentAst     []byte             `db:"content_ast" json:"contentAst"`
	ContentText    string             `db:"content_text" json:"contentText"`
	ChangeSummary  *string            `db:"change_summary" json:"changeSummary"`
	CreatedBy      uuid.UUID          `db:"created_by" json:"createdBy"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"createdAt"`
}

type Project struct {
	ID             uuid.UUID          `db:"id" json:"id"`
	OrganizationID uuid.UUID          `db:"organization_id" json:"organizationId"`
	TeamID         *uuid.UUID         `db:"team_id" json:"teamId"`
	Name           string             `db:"name" json:"name"`
	Slug           string             `db:"slug" json:"slug"`
	Description    *string            `db:"description" json:"description"`
	Visibility     string             `db:"visibility" json:"visibility"`
	IsArchived     bool               `db:"is_archived" json:"isArchived"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"createdAt"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updatedAt"`
}

type ProjectMember struct {
	ProjectID uuid.UUID          `db:"project_id" json:"projectId"`
	UserID    uuid.UUID          `db:"user_id" json:"userId"`
	Role      string             `db:"role" json:"role"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"createdAt"`
}

type ProjectWebhook struct {
	ID             uuid.UUID          `db:"id" json:"id"`
	OrganizationID uuid.UUID          `db:"organization_id" json:"organizationId"`
	ProjectID      uuid.UUID          `db:"project_id" json:"projectId"`
	Platform       string             `db:"platform" json:"platform"`
	WebhookUrl     string             `db:"webhook_url" json:"webhookUrl"`
	Events         []string           `db:"events" json:"events"`
	IsActive       bool               `db:"is_active" json:"isActive"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"createdAt"`
}

type Section struct {
	ID             uuid.UUID          `db:"id" json:"id"`
	OrganizationID uuid.UUID          `db:"organization_id" json:"organizationId"`
	ProjectID      uuid.UUID          `db:"project_id" json:"projectId"`
	Name           string             `db:"name" json:"name"`
	Slug           string             `db:"slug" json:"slug"`
	Position       int32              `db:"position" json:"position"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"createdAt"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updatedAt"`
}

type Team struct {
	ID             uuid.UUID          `db:"id" json:"id"`
	OrganizationID uuid.UUID          `db:"organization_id" json:"organizationId"`
	Name           string             `db:"name" json:"name"`
	Slug           string             `db:"slug" json:"slug"`
	IdpGroupPath   *string            `db:"idp_group_path" json:"idpGroupPath"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"createdAt"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updatedAt"`
}

type TeamMember struct {
	TeamID    uuid.UUID          `db:"team_id" json:"teamId"`
	UserID    uuid.UUID          `db:"user_id" json:"userId"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"createdAt"`
}

type User struct {
	ID          uuid.UUID          `db:"id" json:"id"`
	IdpID       string             `db:"idp_id" json:"idpId"`
	IdpType     string             `db:"idp_type" json:"idpType"`
	Email       string             `db:"email" json:"email"`
	DisplayName string             `db:"display_name" json:"displayName"`
	AvatarUrl   *string            `db:"avatar_url" json:"avatarUrl"`
	IsActive    bool               `db:"is_active" json:"isActive"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"createdAt"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updatedAt"`
}
