// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: organizations.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countOrganizations = `-- name: CountOrganizations :one
SELECT COUNT(*) FROM organizations
`

func (q *Queries) CountOrganizations(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countOrganizations)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO organizations (
    slug,
    name,
    display_name,
    image_url,
    live_url,
    description
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, slug, name, display_name, image_url, live_url, description, created_at, updated_at
`

type CreateOrganizationParams struct {
	Slug        string  `db:"slug" json:"slug"`
	Name        string  `db:"name" json:"name"`
	DisplayName *string `db:"display_name" json:"displayName"`
	ImageUrl    *string `db:"image_url" json:"imageUrl"`
	LiveUrl     *string `db:"live_url" json:"liveUrl"`
	Description *string `db:"description" json:"description"`
}

type CreateOrganizationRow struct {
	ID          uuid.UUID          `db:"id" json:"id"`
	Slug        string             `db:"slug" json:"slug"`
	Name        string             `db:"name" json:"name"`
	DisplayName *string            `db:"display_name" json:"displayName"`
	ImageUrl    *string            `db:"image_url" json:"imageUrl"`
	LiveUrl     *string            `db:"live_url" json:"liveUrl"`
	Description *string            `db:"description" json:"description"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"createdAt"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updatedAt"`
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (CreateOrganizationRow, error) {
	row := q.db.QueryRow(ctx, createOrganization,
		arg.Slug,
		arg.Name,
		arg.DisplayName,
		arg.ImageUrl,
		arg.LiveUrl,
		arg.Description,
	)
	var i CreateOrganizationRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.DisplayName,
		&i.ImageUrl,
		&i.LiveUrl,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteOrganization = `-- name: DeleteOrganization :exec
DELETE FROM organizations
WHERE id = $1
`

func (q *Queries) DeleteOrganization(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteOrganization, id)
	return err
}

const getOrganizationByID = `-- name: GetOrganizationByID :one
SELECT id, slug, name, display_name, image_url, live_url, description, created_at, updated_at
FROM organizations
WHERE id = $1
`

type GetOrganizationByIDRow struct {
	ID          uuid.UUID          `db:"id" json:"id"`
	Slug        string             `db:"slug" json:"slug"`
	Name        string             `db:"name" json:"name"`
	DisplayName *string            `db:"display_name" json:"displayName"`
	ImageUrl    *string            `db:"image_url" json:"imageUrl"`
	LiveUrl     *string            `db:"live_url" json:"liveUrl"`
	Description *string            `db:"description" json:"description"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"createdAt"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updatedAt"`
}

func (q *Queries) GetOrganizationByID(ctx context.Context, id uuid.UUID) (GetOrganizationByIDRow, error) {
	row := q.db.QueryRow(ctx, getOrganizationByID, id)
	var i GetOrganizationByIDRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.DisplayName,
		&i.ImageUrl,
		&i.LiveUrl,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizationBySlug = `-- name: GetOrganizationBySlug :one
SELECT id, slug, name, display_name, image_url, live_url, description, created_at, updated_at
FROM organizations
WHERE slug = $1
`

type GetOrganizationBySlugRow struct {
	ID          uuid.UUID          `db:"id" json:"id"`
	Slug        string             `db:"slug" json:"slug"`
	Name        string             `db:"name" json:"name"`
	DisplayName *string            `db:"display_name" json:"displayName"`
	ImageUrl    *string            `db:"image_url" json:"imageUrl"`
	LiveUrl     *string            `db:"live_url" json:"liveUrl"`
	Description *string            `db:"description" json:"description"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"createdAt"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updatedAt"`
}

func (q *Queries) GetOrganizationBySlug(ctx context.Context, slug string) (GetOrganizationBySlugRow, error) {
	row := q.db.QueryRow(ctx, getOrganizationBySlug, slug)
	var i GetOrganizationBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.DisplayName,
		&i.ImageUrl,
		&i.LiveUrl,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOrganizations = `-- name: ListOrganizations :many
SELECT id, slug, name, display_name, image_url, live_url, description, created_at, updated_at
FROM organizations
ORDER BY name ASC
LIMIT $1 OFFSET $2
`

type ListOrganizationsParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

type ListOrganizationsRow struct {
	ID          uuid.UUID          `db:"id" json:"id"`
	Slug        string             `db:"slug" json:"slug"`
	Name        string             `db:"name" json:"name"`
	DisplayName *string            `db:"display_name" json:"displayName"`
	ImageUrl    *string            `db:"image_url" json:"imageUrl"`
	LiveUrl     *string            `db:"live_url" json:"liveUrl"`
	Description *string            `db:"description" json:"description"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"createdAt"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updatedAt"`
}

func (q *Queries) ListOrganizations(ctx context.Context, arg ListOrganizationsParams) ([]ListOrganizationsRow, error) {
	rows, err := q.db.Query(ctx, listOrganizations, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrganizationsRow
	for rows.Next() {
		var i ListOrganizationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.DisplayName,
			&i.ImageUrl,
			&i.LiveUrl,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrganization = `-- name: UpdateOrganization :one
UPDATE organizations
SET
    name = COALESCE($2, name),
    display_name = COALESCE($3, display_name),
    image_url = COALESCE($4, image_url),
    live_url = COALESCE($5, live_url),
    description = COALESCE($6, description),
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, slug, name, display_name, image_url, live_url, description, created_at, updated_at
`

type UpdateOrganizationParams struct {
	ID          uuid.UUID `db:"id" json:"id"`
	Name        string    `db:"name" json:"name"`
	DisplayName *string   `db:"display_name" json:"displayName"`
	ImageUrl    *string   `db:"image_url" json:"imageUrl"`
	LiveUrl     *string   `db:"live_url" json:"liveUrl"`
	Description *string   `db:"description" json:"description"`
}

type UpdateOrganizationRow struct {
	ID          uuid.UUID          `db:"id" json:"id"`
	Slug        string             `db:"slug" json:"slug"`
	Name        string             `db:"name" json:"name"`
	DisplayName *string            `db:"display_name" json:"displayName"`
	ImageUrl    *string            `db:"image_url" json:"imageUrl"`
	LiveUrl     *string            `db:"live_url" json:"liveUrl"`
	Description *string            `db:"description" json:"description"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"createdAt"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updatedAt"`
}

func (q *Queries) UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) (UpdateOrganizationRow, error) {
	row := q.db.QueryRow(ctx, updateOrganization,
		arg.ID,
		arg.Name,
		arg.DisplayName,
		arg.ImageUrl,
		arg.LiveUrl,
		arg.Description,
	)
	var i UpdateOrganizationRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.DisplayName,
		&i.ImageUrl,
		&i.LiveUrl,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
