// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pages.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getPageByID = `-- name: GetPageByID :one
SELECT id, organization_id, project_id, section_id, parent_id, title, slug, path, position,
current_published_version, has_draft, is_restricted, is_archived, created_by, created_at, updated_at
FROM pages
WHERE id = $1
`

func (q *Queries) GetPageByID(ctx context.Context, id uuid.UUID) (Page, error) {
	row := q.db.QueryRow(ctx, getPageByID, id)
	var i Page
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.SectionID,
		&i.ParentID,
		&i.Title,
		&i.Slug,
		&i.Path,
		&i.Position,
		&i.CurrentPublishedVersion,
		&i.HasDraft,
		&i.IsRestricted,
		&i.IsArchived,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPagesByProject = `-- name: ListPagesByProject :many
SELECT id, organization_id, project_id, section_id, parent_id, title, slug, path, position,
current_published_version, has_draft, is_restricted, is_archived, created_by, created_at, updated_at
FROM pages
WHERE project_id = $1
ORDER BY position ASC
`

func (q *Queries) ListPagesByProject(ctx context.Context, projectID uuid.UUID) ([]Page, error) {
	rows, err := q.db.Query(ctx, listPagesByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Page
	for rows.Next() {
		var i Page
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ProjectID,
			&i.SectionID,
			&i.ParentID,
			&i.Title,
			&i.Slug,
			&i.Path,
			&i.Position,
			&i.CurrentPublishedVersion,
			&i.HasDraft,
			&i.IsRestricted,
			&i.IsArchived,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
