// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const countProjectsByOrg = `-- name: CountProjectsByOrg :one
SELECT COUNT(*) FROM projects WHERE organization_id = $1 AND is_archived = FALSE
`

func (q *Queries) CountProjectsByOrg(ctx context.Context, organizationID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countProjectsByOrg, organizationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (
    organization_id,
    team_id,
    name,
    slug,
    description,
    visibility
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, organization_id, team_id, name, slug, description, visibility, is_archived, created_at, updated_at
`

type CreateProjectParams struct {
	OrganizationID uuid.UUID  `db:"organization_id" json:"organizationId"`
	TeamID         *uuid.UUID `db:"team_id" json:"teamId"`
	Name           string     `db:"name" json:"name"`
	Slug           string     `db:"slug" json:"slug"`
	Description    *string    `db:"description" json:"description"`
	Visibility     string     `db:"visibility" json:"visibility"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.OrganizationID,
		arg.TeamID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.Visibility,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.TeamID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Visibility,
		&i.IsArchived,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects
WHERE id = $1
`

func (q *Queries) DeleteProject(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProject, id)
	return err
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT id, organization_id, team_id, name, slug, description, visibility, is_archived, created_at, updated_at
FROM projects
WHERE id = $1
`

func (q *Queries) GetProjectByID(ctx context.Context, id uuid.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByID, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.TeamID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Visibility,
		&i.IsArchived,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectBySlug = `-- name: GetProjectBySlug :one
SELECT id, organization_id, team_id, name, slug, description, visibility, is_archived, created_at, updated_at
FROM projects
WHERE organization_id = $1 AND slug = $2
`

type GetProjectBySlugParams struct {
	OrganizationID uuid.UUID `db:"organization_id" json:"organizationId"`
	Slug           string    `db:"slug" json:"slug"`
}

func (q *Queries) GetProjectBySlug(ctx context.Context, arg GetProjectBySlugParams) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectBySlug, arg.OrganizationID, arg.Slug)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.TeamID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Visibility,
		&i.IsArchived,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProjectsByOrg = `-- name: ListProjectsByOrg :many
SELECT id, organization_id, team_id, name, slug, description, visibility, is_archived, created_at, updated_at
FROM projects
WHERE organization_id = $1 AND is_archived = FALSE
ORDER BY name ASC
LIMIT $2 OFFSET $3
`

type ListProjectsByOrgParams struct {
	OrganizationID uuid.UUID `db:"organization_id" json:"organizationId"`
	Limit          int32     `db:"limit" json:"limit"`
	Offset         int32     `db:"offset" json:"offset"`
}

func (q *Queries) ListProjectsByOrg(ctx context.Context, arg ListProjectsByOrgParams) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjectsByOrg, arg.OrganizationID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.TeamID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Visibility,
			&i.IsArchived,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET
    name = COALESCE($2, name),
    description = COALESCE($3, description),
    visibility = COALESCE($4, visibility),
    team_id = COALESCE($5, team_id),
    is_archived = COALESCE($6, is_archived),
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, organization_id, team_id, name, slug, description, visibility, is_archived, created_at, updated_at
`

type UpdateProjectParams struct {
	ID          uuid.UUID  `db:"id" json:"id"`
	Name        string     `db:"name" json:"name"`
	Description *string    `db:"description" json:"description"`
	Visibility  string     `db:"visibility" json:"visibility"`
	TeamID      *uuid.UUID `db:"team_id" json:"teamId"`
	IsArchived  bool       `db:"is_archived" json:"isArchived"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Visibility,
		arg.TeamID,
		arg.IsArchived,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.TeamID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Visibility,
		&i.IsArchived,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
