// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (CreateOrganizationRow, error)
	GetOrganizationByID(ctx context.Context, id uuid.UUID) (GetOrganizationByIDRow, error)
	GetOrganizationBySlug(ctx context.Context, slug string) (GetOrganizationBySlugRow, error)
	GetPageByID(ctx context.Context, id uuid.UUID) (Page, error)
	ListOrganizations(ctx context.Context) ([]ListOrganizationsRow, error)
	ListPagesByProject(ctx context.Context, projectID uuid.UUID) ([]Page, error)
	UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) (UpdateOrganizationRow, error)
}

var _ Querier = (*Queries)(nil)
