// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sections.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createSection = `-- name: CreateSection :one
INSERT INTO sections (
    organization_id,
    project_id,
    name,
    slug,
    position
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, organization_id, project_id, name, slug, position, created_at, updated_at
`

type CreateSectionParams struct {
	OrganizationID uuid.UUID `db:"organization_id" json:"organizationId"`
	ProjectID      uuid.UUID `db:"project_id" json:"projectId"`
	Name           string    `db:"name" json:"name"`
	Slug           string    `db:"slug" json:"slug"`
	Position       int32     `db:"position" json:"position"`
}

func (q *Queries) CreateSection(ctx context.Context, arg CreateSectionParams) (Section, error) {
	row := q.db.QueryRow(ctx, createSection,
		arg.OrganizationID,
		arg.ProjectID,
		arg.Name,
		arg.Slug,
		arg.Position,
	)
	var i Section
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.Name,
		&i.Slug,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSection = `-- name: DeleteSection :exec
DELETE FROM sections
WHERE id = $1
`

func (q *Queries) DeleteSection(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSection, id)
	return err
}

const getSectionByID = `-- name: GetSectionByID :one
SELECT id, organization_id, project_id, name, slug, position, created_at, updated_at
FROM sections
WHERE id = $1
`

func (q *Queries) GetSectionByID(ctx context.Context, id uuid.UUID) (Section, error) {
	row := q.db.QueryRow(ctx, getSectionByID, id)
	var i Section
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.Name,
		&i.Slug,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSectionsByProject = `-- name: ListSectionsByProject :many
SELECT id, organization_id, project_id, name, slug, position, created_at, updated_at
FROM sections
WHERE project_id = $1
ORDER BY position ASC, name ASC
`

func (q *Queries) ListSectionsByProject(ctx context.Context, projectID uuid.UUID) ([]Section, error) {
	rows, err := q.db.Query(ctx, listSectionsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Section
	for rows.Next() {
		var i Section
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ProjectID,
			&i.Name,
			&i.Slug,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSection = `-- name: UpdateSection :one
UPDATE sections
SET
    name = COALESCE($2, name),
    position = COALESCE($3, position),
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, organization_id, project_id, name, slug, position, created_at, updated_at
`

type UpdateSectionParams struct {
	ID       uuid.UUID `db:"id" json:"id"`
	Name     string    `db:"name" json:"name"`
	Position int32     `db:"position" json:"position"`
}

func (q *Queries) UpdateSection(ctx context.Context, arg UpdateSectionParams) (Section, error) {
	row := q.db.QueryRow(ctx, updateSection, arg.ID, arg.Name, arg.Position)
	var i Section
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.Name,
		&i.Slug,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
