// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: teams.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const countTeamsByOrg = `-- name: CountTeamsByOrg :one
SELECT COUNT(*) FROM teams WHERE organization_id = $1
`

func (q *Queries) CountTeamsByOrg(ctx context.Context, organizationID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countTeamsByOrg, organizationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTeam = `-- name: CreateTeam :one
INSERT INTO teams (
    organization_id,
    name,
    slug,
    idp_group_path
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, organization_id, name, slug, idp_group_path, created_at, updated_at
`

type CreateTeamParams struct {
	OrganizationID uuid.UUID `db:"organization_id" json:"organizationId"`
	Name           string    `db:"name" json:"name"`
	Slug           string    `db:"slug" json:"slug"`
	IdpGroupPath   *string   `db:"idp_group_path" json:"idpGroupPath"`
}

func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error) {
	row := q.db.QueryRow(ctx, createTeam,
		arg.OrganizationID,
		arg.Name,
		arg.Slug,
		arg.IdpGroupPath,
	)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Slug,
		&i.IdpGroupPath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTeam = `-- name: DeleteTeam :exec
DELETE FROM teams
WHERE id = $1
`

func (q *Queries) DeleteTeam(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTeam, id)
	return err
}

const getTeamByID = `-- name: GetTeamByID :one
SELECT id, organization_id, name, slug, idp_group_path, created_at, updated_at
FROM teams
WHERE id = $1
`

func (q *Queries) GetTeamByID(ctx context.Context, id uuid.UUID) (Team, error) {
	row := q.db.QueryRow(ctx, getTeamByID, id)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Slug,
		&i.IdpGroupPath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTeamBySlug = `-- name: GetTeamBySlug :one
SELECT id, organization_id, name, slug, idp_group_path, created_at, updated_at
FROM teams
WHERE organization_id = $1 AND slug = $2
`

type GetTeamBySlugParams struct {
	OrganizationID uuid.UUID `db:"organization_id" json:"organizationId"`
	Slug           string    `db:"slug" json:"slug"`
}

func (q *Queries) GetTeamBySlug(ctx context.Context, arg GetTeamBySlugParams) (Team, error) {
	row := q.db.QueryRow(ctx, getTeamBySlug, arg.OrganizationID, arg.Slug)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Slug,
		&i.IdpGroupPath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTeamsByOrg = `-- name: ListTeamsByOrg :many
SELECT id, organization_id, name, slug, idp_group_path, created_at, updated_at
FROM teams
WHERE organization_id = $1
ORDER BY name ASC
LIMIT $2 OFFSET $3
`

type ListTeamsByOrgParams struct {
	OrganizationID uuid.UUID `db:"organization_id" json:"organizationId"`
	Limit          int32     `db:"limit" json:"limit"`
	Offset         int32     `db:"offset" json:"offset"`
}

func (q *Queries) ListTeamsByOrg(ctx context.Context, arg ListTeamsByOrgParams) ([]Team, error) {
	rows, err := q.db.Query(ctx, listTeamsByOrg, arg.OrganizationID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Team
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.Slug,
			&i.IdpGroupPath,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTeam = `-- name: UpdateTeam :one
UPDATE teams
SET
    name = COALESCE($2, name),
    idp_group_path = COALESCE($3, idp_group_path),
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, organization_id, name, slug, idp_group_path, created_at, updated_at
`

type UpdateTeamParams struct {
	ID           uuid.UUID `db:"id" json:"id"`
	Name         string    `db:"name" json:"name"`
	IdpGroupPath *string   `db:"idp_group_path" json:"idpGroupPath"`
}

func (q *Queries) UpdateTeam(ctx context.Context, arg UpdateTeamParams) (Team, error) {
	row := q.db.QueryRow(ctx, updateTeam, arg.ID, arg.Name, arg.IdpGroupPath)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Slug,
		&i.IdpGroupPath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
